version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 12
    versioning-strategy: widen
    groups:
      prisma:
        patterns:
          - "@prisma/*"
          - "prisma"
      otel:
        patterns:
          - "@opentelemetry/*"
      upstash:
        patterns:
          - "@upstash/*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
